/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.LombookDTO;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;

public class App {
       public static void main(String[] args) {
      Categoria cat1 = Categoria.builder().nombre("Electrónica").descripcion("Dispositivos electrónicos").build();
      Categoria cat2 = Categoria.builder().nombre("Ropa").descripcion("Indumentaria").build();
      Categoria cat3 = Categoria.builder().nombre("Libros").descripcion("Lectura y estudio").build();

      Producto p1 = Producto.builder().nombre("Notebook").precio(1000.0).descripcion("Laptop 15''").stock(5).imagen("notebook.jpg").disponible(true).categoria(cat1).build();
      Producto p2 = Producto.builder().nombre("Smartphone").precio(800.0).descripcion("Android 6''").stock(10).imagen("phone.jpg").disponible(true).categoria(cat1).build();
      Producto p3 = Producto.builder().nombre("Auriculares").precio(50.0).descripcion("Bluetooth").stock(20).imagen("auris.jpg").disponible(true).categoria(cat1).build();
      Producto p4 = Producto.builder().nombre("Remera").precio(20.0).descripcion("Algodón").stock(30).imagen("remera.jpg").disponible(true).categoria(cat2).build();
      Producto p5 = Producto.builder().nombre("Pantalón").precio(40.0).descripcion("Jean").stock(15).imagen("pantalon.jpg").disponible(true).categoria(cat2).build();
      Producto p6 = Producto.builder().nombre("Campera").precio(60.0).descripcion("Abrigo").stock(8).imagen("campera.jpg").disponible(true).categoria(cat2).build();
      Producto p7 = Producto.builder().nombre("Libro Java").precio(35.0).descripcion("Programación Java").stock(12).imagen("java.jpg").disponible(true).categoria(cat3).build();
      Producto p8 = Producto.builder().nombre("Libro Python").precio(30.0).descripcion("Programación Python").stock(10).imagen("python.jpg").disponible(true).categoria(cat3).build();
      Producto p9 = Producto.builder().nombre("Libro SQL").precio(25.0).descripcion("Bases de datos").stock(7).imagen("sql.jpg").disponible(true).categoria(cat3).build();
      Producto p10 = Producto.builder().nombre("Tablet").precio(400.0).descripcion("Tablet 10''").stock(6).imagen("tablet.jpg").disponible(true).categoria(cat1).build();

      List<Producto> productos = Arrays.asList(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10);

      Usuario u1 = Usuario.builder()
         .nombre("Ramiro")
         .apellido("Morales")
         .mail("rami@gmail.com")
         .celular("3412119580")
         .contraseña("123456")
         .rol(Rol.USUARIO)
         .build();
      Usuario u2 = Usuario.builder()
         .nombre("Belen")
         .apellido("Torres")
         .mail("belu@gmail.com")
         .celular("3412119000")
         .contraseña("abcdef")
         .rol(Rol.ADMIN)
         .build();

      // Asociar pedidos a usuarios
      List<Pedido> pedidosU1 = new ArrayList<>();
      List<Pedido> pedidosU2 = new ArrayList<>();

      Pedido pedido1 = Pedido.builder()
         .fecha(LocalDate.now())
         .estado(Estado.PENDIENTE)
         .formaPago(FormaPago.TARJETA)
         .detalles(new ArrayList<>(Arrays.asList(
            DetallePedido.builder().producto(p1).cantidad(1).subtotal(p1.getPrecio() * 1).build(),
            DetallePedido.builder().producto(p4).cantidad(2).subtotal(p4.getPrecio() * 2).build()
         )))
         .build();
      pedido1.calcularTotal();
      pedidosU1.add(pedido1);

      Pedido pedido2 = Pedido.builder()
         .fecha(LocalDate.now())
         .estado(Estado.CONFIRMADO)
         .formaPago(FormaPago.TRANSFERENCIA)
         .detalles(new ArrayList<>(Arrays.asList(
            DetallePedido.builder().producto(p2).cantidad(1).subtotal(p2.getPrecio() * 1).build(),
            DetallePedido.builder().producto(p5).cantidad(3).subtotal(p5.getPrecio() * 3).build(),
            DetallePedido.builder().producto(p7).cantidad(1).subtotal(p7.getPrecio() * 1).build()
         )))
         .build();
      pedido2.calcularTotal();
      pedidosU1.add(pedido2);

      Pedido pedido3 = Pedido.builder()
         .fecha(LocalDate.now())
         .estado(Estado.TERMINADO)
         .formaPago(FormaPago.EFECTIVO)
         .detalles(new ArrayList<>(Arrays.asList(
            DetallePedido.builder().producto(p3).cantidad(2).subtotal(p3.getPrecio() * 2).build(),
            DetallePedido.builder().producto(p8).cantidad(1).subtotal(p8.getPrecio() * 1).build()
         )))
         .build();
      pedido3.calcularTotal();
      pedidosU2.add(pedido3);

      // Mostrar un producto
      System.out.println("\n--- Un producto ---");
      System.out.println(p1);

      // Mostrar listado de productos
      System.out.println("\n--- Listado de productos ---");
      for (Producto prod : productos) {
          System.out.println(prod);
      }

        // Determinar usuario con más pedidos
        Usuario usuarioMasPedidos = pedidosU1.size() >= pedidosU2.size() ? u1 : u2;
        List<Pedido> pedidosMas = pedidosU1.size() >= pedidosU2.size() ? pedidosU1 : pedidosU2;

        System.out.println("\n--- Usuario con más pedidos: " + usuarioMasPedidos.getNombre() + " " + usuarioMasPedidos.getApellido() + " ---");
        for (Pedido ped : pedidosMas) {
           System.out.println(ped);
        }

        // Instanciar un producto igual a otro (por equals) y comparar con todos los productos
        Producto productoIgual = Producto.builder()
              .nombre("Notebook")
              .precio(1000.0)
              .descripcion("Laptop 15''")
              .stock(5)
              .imagen("notebook.jpg")
              .disponible(true)
              .categoria(cat1)
              .build();

        System.out.println("\n Comparación de producto con la colección de productos");
        for (Producto prod : productos) {
           boolean esIgual = productoIgual.equals(prod);
           System.out.println("Su contenido es igual a:  " + prod.getNombre() + "? " + esIgual);
        }
       }
}
